### ISSUE TITLE
"Foundation.MonoTouchException: Objective-C exception" thrown when change page after drag a pin

### ISSUE THREAD

**Issue by neumartin** [TorbenK/TK.CustomMap#163] opened 2016-12-27 02:15 UTC
Hi!

In the release 1.5.1 when I drag a pin and use the PinDragEnd event, when I change the page "App.Current.MainPage = ...." I get this error:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: Cannot remove an observer <MKMapAnnotationManager 0x610001d2a140> for the key path "coordinate" from <TK_CustomMap_iOSUnified_TKCustomMapAnnotation 0x608000416650> because it is not registered as an observer.

Native stack trace:
	0   CoreFoundation                      0x0000000107738d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001121c421e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001077a22b5 +[NSException raise:format:] + 197
	3   Foundation                          0x00000001082a0ba8 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 493
	4   Foundation                          0x00000001082a0962 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
	5   MapKit                              0x000000010a28c527 __30-[MKAnnotationManager dealloc]_block_invoke + 34
	6   MapKit                              0x000000010a2a4231 __22-[MKQuadTrie foreach:]_block_invoke + 77
	7   MapKit                              0x000000010a2a3d55 _Z18_breadthFirstApplyP14MKQuadTrieNodeU13block_pointerF28MKQuadTrieTraversalDirectiveS0_E + 164
	8   MapKit                              0x000000010a2a348e -[MKQuadTrie foreach:] + 112
	9   MapKit                              0x000000010a288e1c -[MKAnnotationManager dealloc] + 154
	10  libobjc.A.dylib                     0x00000001121d8b12 _ZN11objc_object17sidetable_releaseEb + 212
	11  MapKit                              0x000000010a1ceec2 -[MKMapView .cxx_destruct] + 687
	12  libobjc.A.dylib                     0x00000001121c2a0a _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	13  libobjc.A.dylib                     0x00000001121ce5f6 objc_destructInstance + 129
	14  libobjc.A.dylib                     0x00000001121ce628 object_dispose + 22
	15  UIKit                               0x000000010b22adc2 -[UIResponder dealloc] + 146
	16  UIKit                               0x000000010b0a9e74 -[UIView dealloc] + 1916
	17  MapKit                              0x000000010a1b79bb -[MKMapView dealloc] + 636
	18  libobjc.A.dylib                     0x00000001121d91d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	19  UIKit                               0x000000010b0a9e4c -[UIView dealloc] + 1876
	20  SinVueltas.App.iOS                  0x00000001070ba30b xamarin_invoke_objc_method_implementation + 59
	21  SinVueltas.App.iOS                  0x00000001070ba48b xamarin_release_trampoline + 155
	22  CoreFoundation                      0x000000010779025e common_removeAllObjects + 254
	23  CoreFoundation                      0x000000010766cc93 -[__NSArrayM dealloc] + 19
	24  libobjc.A.dylib                     0x00000001121d8b12 _ZN11objc_object17sidetable_releaseEb + 212
	25  libobjc.A.dylib                     0x00000001121d91d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	26  CoreFoundation                      0x0000000107685676 _CFAutoreleasePoolPop + 22
	27  Foundation                          0x00000001082b6f5b __NSThreadPerformPerform + 515
	28  CoreFoundation                      0x00000001076dd761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	29  CoreFoundation                      0x00000001076c298c __CFRunLoopDoSources0 + 556
	30  CoreFoundation                      0x00000001076c1e76 __CFRunLoopRun + 918
	31  CoreFoundation                      0x00000001076c1884 CFRunLoopRunSpecific + 420
	32  GraphicsServices                    0x0000000114e78a6f GSEventRunModal + 161
	33  UIKit                               0x000000010b013c68 UIApplicationMain + 159
	34  ???                                 0x00000001277fc65c 0x0 + 4957652572
	35  ???                                 0x000000012a345e4d 0x0 + 5003042381

**Comment by neumartin** [comment] 2016-12-27 02:16
I try:

```
foreach (TKCustomMapPin pin in pins.ToList())
	pins.Remove(pin);

foreach (Pin pin in mapView.Pins.ToList())
	mapView.Pins.Remove(pin);

mapView.PinDragEnd += null;
```

But keep failing...

**Comment by jfversluis** [comment] 2016-12-27 08:00
Why are you doing `mapView.PinDragEnd += null;`?

Shouldn't this be something like `mapView.PinDragEnd -= PinDragEndHandler;`

**Comment by neumartin** [comment] 2016-12-27 13:19
Hi!

I tryed, but same error.

     mapView.PinDragEnd -= MapView_PinDragEnd;
     mapView = null;

The error only happend when I drag a pin and later go to another page.
Thanks!

**Comment by jfversluis** [comment] 2016-12-27 13:31
Could you create a sample project demonstrating this bug? Then we can have a look at it.

**Comment by neumartin** [comment] 2016-12-27 14:33
Ok, you can download the sample from: http://www.neumartin.com.ar/Files/SampleDragPinError.rar

First drag the pin, later press the button for go to page 2.
Thanks a lot!!!

**Comment by neumartin** [comment] 2016-12-29 15:55
Hi!

Any release date for the fix?
Thanks!

**Comment by jfversluis** [comment] 2016-12-29 16:32
Nope sorry! Although I can see it goes wrong I cannot pinpoint where it goes wrong, so I can't make any promises. You are more than welcome to investigate some more yourself and provide a solution :)

**Comment by Sagariouz** [comment] 2017-01-11 10:11
Yeah, getting the same exception. Did anyone get it working?

In our scenario, the map is in a Popup and it occurs when the popup closes, in essence when disposing of the mapview. So it is interesting that it happens when you push a new page... But in any case, we dont use an event, pretty much just the map and a pin.

Cloned the repo and I'm still investigating.

**Comment by TorbenK** [comment] 2017-01-11 11:31
I just pushed a fix. You should be able to work around this issue by adding a own renderer:

```
public class MyMapRenderer : TKCustomMapRenderer
{
	protected override void Dispose(bool disposing)
	{
		var map = Control as MKMapView;

		if (map != null)
		{
			map.RemoveAnnotations(map.Annotations);
		}

		base.Dispose(disposing);
	}
}
```

**Comment by TorbenK** [comment] 2017-01-27 07:43
#159
This fix is probably the root cause of the whole thing.

**Comment by TorbenK** [comment] 2017-01-30 12:00
1.5.1

**Closed as completed by TorbenK** 2017-01-30 12:00 UTC
Labels: bug
