### ISSUE TITLE
Pin position is not changed on iOS

### ISSUE THREAD

**Issue by hopewise** [TorbenK/TK.CustomMap#88] opened 2016-05-22 09:35 UTC
Changing pin `Position`at android target works fine, however changing the pin `Position`will not effect the pin location at map in iOS, it seems that the pin `Position`binding is not working for iOS ?! :cry:

**Comment by TorbenK** [comment] 2016-05-23 06:43
Thanks for reporting this, I will investigate and release a hotfix if this is really the case.

**Comment by hopewise** [comment] 2016-05-23 07:48
Thank you, we will be waiting to test the hotfix.
Actually, a very important decision is literary pending because of this issue!

**Comment by ahmedkhan25** [comment] 2016-06-22 21:39
Is this issue fixed? I'm seeing this issue in iOS in the latest nuget (1.5.0) - if i can't find a workaround by next week I wont be able to use this package in my app.. 

thanks!

**Comment by TorbenK** [comment] 2016-06-23 07:47
Hello. I did changes regarding this but I didn't test it yet. There is also no nuget package avaiable containing the fix. You can, of course, download the dev branch and do your own build. I don't think I'll be able to work on this next two weeks.

**Comment by ahmedkhan25** [comment] 2016-06-23 18:12
Ok - I  downloaded the latest Dev Branch used those updated libs in my Xamarin Forms project - However I'm still seeing a lack of update for pin position when zooming the map in or out. See attached movie of the map running on android device. Any Suggestions?? -is there some way to manually update the pin position on zoom or pinch?  I'm about to release the app to my client next week. 

Movie of issue: https://www.dropbox.com/s/gnanxmym1nvt0mx/TKMapPinError.mov?dl=0

**Comment by TorbenK** [comment] 2016-07-12 21:02
I'm not able to reproduce this. It looks like your pin is static on some screen coordinates, I actually don't know what is going on there and I dont think it is atually related to this issue.

The issue with the pin not moving on iOS when the position is changed, it will be fixed in the next release.

**Comment by TorbenK** [comment] 2017-01-30 12:03
1.5.1.

**Closed as completed by TorbenK** 2017-01-30 12:03 UTC
Labels: bug
