### ISSUE TITLE
Update my GooglePlayServices Package and TK.CustomMap no fired on release compile

### ISSUE THREAD

**Issue by Micnick** [TorbenK/TK.CustomMap#233] opened 2017-07-23 23:50 UTC
Hi, guys

I Have an error on Release compile, but in Debug compile be fine

Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Gms.Location.Places.IAutocompletePrediction' (defined in assembly 'TK.CustomMap.Android, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Location, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Location.Places.IAutocompletePrediction
   en Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference) en /Users/builder/data/lanes/4695/9dbc4c53/source/xamarin-android/external/linker/linker/Mono.Linker.Steps/MarkStep.cs:línea 523

**Comment by rohitvipin** [comment] 2017-08-15 14:38
Duplicate of https://github.com/TorbenK/TK.CustomMap/issues/210

**Closed as completed** 2017-10-25 10:01 UTC
