### ISSUE TITLE
Default constructor not found

### ISSUE THREAD

**Issue by dimeom** [TorbenK/TK.CustomMap#77] opened 2016-05-14 10:00 UTC
Hi,

I am working with Tk.CustomMap on Xamarin Forms XAML. and I am getting this error:

System.MissingMethodException: Default constructor not found for type TK.CustomMap.TKCustomMap

When I open the page which contains the map, that error shows up and my app closes.

I have uninstall the nugget, and reinstalled, I have done all the settings correctly, still I cant get it to work .

Please help!

My XAML looks like this:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:test;assembly=test"
             xmlns:customMap="clr-namespace:TK.CustomMap;assembly=TK.CustomMap"
             x:Class="tetst.pageMap">

  <ContentPage.Content>

```
<Grid RowSpacing="0" ColumnSpacing="0" BackgroundColor="{DynamicResource bgColor}">

  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="1*"/>
    <ColumnDefinition Width="1*"/>
    <ColumnDefinition Width="1*"/>
    <ColumnDefinition Width="1*"/>
  </Grid.ColumnDefinitions>

  <Grid.RowDefinitions>
    <RowDefinition Height="1*"/>
    <!--header-->
    <RowDefinition Height="7*"/>

    <RowDefinition Height="1*"/>

  </Grid.RowDefinitions>

  <!--Header-->
  <Grid RowSpacing="0" ColumnSpacing="0" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="4" BackgroundColor="{DynamicResource bgColor}">
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="6*"/>
      <ColumnDefinition Width="1*"/>
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
      <RowDefinition Height="1*"/>
    </Grid.RowDefinitions>

    <BoxView Style="{DynamicResource boxViewHeader}" Grid.ColumnSpan="2" />
    <Image x:Name="imgLogoName" Grid.Row="0"  Grid.ColumnSpan="2" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"></Image>
    <Image x:Name="imgLogo" Grid.Column="1" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"></Image>
    <Image x:Name="imageBack" Grid.Row="0" Grid.Column="0" VerticalOptions="EndAndExpand" HorizontalOptions="StartAndExpand">
      <Image.GestureRecognizers>
        <TapGestureRecognizer
                Tapped="imageBack_Tapped"
                NumberOfTapsRequired="1" />
      </Image.GestureRecognizers>
    </Image>
  </Grid>
  <!--Header-->

  <Grid Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="4">
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="1*"/>
    </Grid.ColumnDefinitions>

    <Grid.RowDefinitions>
      <RowDefinition Height="1*"/>

    </Grid.RowDefinitions>

    <customMap:TKCustomMap x:Name="MyMap" MapType="Street" Grid.Row="0" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />

  </Grid>

  <Label x:Name="lblStart" Text="Schorlejagd starten" Grid.Row="2" Grid.Column="1" Grid.ColumnSpan="3" VerticalOptions="FillAndExpand" HorizontalOptions="Center"></Label>

  <Image x:Name="btnStart" Grid.Row="2" Grid.Column="0" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
    <Image.GestureRecognizers>
      <TapGestureRecognizer
              Tapped="btnStart_Tapped"
              NumberOfTapsRequired="1" />
    </Image.GestureRecognizers>
  </Image>
</Grid>
```

  </ContentPage.Content>
</ContentPage>

and my code:

```
            Geocoder geo = new Geocoder();
            List<TKCustomMapPin> pins = new List<TKCustomMapPin>();
            foreach (LocationObject location in Globals.Places)
            {
                var position = new Position(double.Parse(location.Latitude.ToString()), double.Parse(location.Longitude.ToString()));
                var pin = new TKCustomMapPin();
                pin.Position = position;
                pin.Title = location.Name;
                pin.Image = Device.OnPlatform("wine.png", "wine.png", "Assets/wine.png");

                pins.Add(pin);
            }

            MyMap.CustomPins = pins;
```

**Comment by TorbenK** [comment] 2016-05-15 18:44
I am unable to reproduce this. Do you call

`TK.CustomMap.iOSUnified.TKCustomMapRenderer.InitMapRenderer();`

In your iOS project?

**Comment by dimeom** [comment] 2016-05-15 18:47
Hi, yes. But I am having this problem on Android. I havent tested on iOS.

I thought that maybe I have to do the same on android (InitMapRender)

**Comment by TorbenK** [comment] 2016-05-15 18:56
I'm unable to reproduce it on Android either. Can you share a little repro project?

**Comment by dimeom** [comment] 2016-05-15 20:41
Thanks for your patience and help!

I reinstalled every single nugget... and guess what.. now it works! :)

now the pin comes with the custom image. but the title is not being displayed after tapping the pin.

**Comment by TorbenK** [comment] 2016-05-15 21:28
Please look at the samples. `ShowCallout` needs to be `true`.

I will close this issue.

**Closed as completed by TorbenK** 2016-05-15 21:28 UTC

**Comment by dimeom** [comment] 2016-05-15 21:53
thanks a lot!! :) :+1:
