### ISSUE TITLE
Android Map crashes

### ISSUE THREAD

**Issue by tomzwo** [TorbenK/TK.CustomMap#207] opened 2017-03-15 15:52 UTC
(hopefully, I don't break any courtesy rules by jumping right into the problem; I'm new here)

displaying a map crashes with
Method 'Android.Gms.Maps.MapView.get_Map' not found.
...
 at TK.CustomMap.Droid.TKCustomMapRenderer.OnElementChanged 

the map itself _has_ been working but stopped to after the latest Xamarin updates

I'm using V1.5.1 from NuGet

I did some background digging; apparently, at the core lies this Xamarin bug https://bugzilla.xamarin.com/show_bug.cgi?id=52625
and the workaround(s) discussed there all recommend using async map access instead of the (previously deprecated, now dropped) method which is not found (as above).

If I look at the code in TKCustomMapRenderer.OnElementChanged(), is seems to use async access to the map

Right now, I'm at the end of my wits - any ideas, anybody?

kind regards
Tom

**Comment by PhilJenson** [comment] 2017-03-27 16:40
I have the same problem. This is an issue which occurs when using v25.2.0 of Xamarin.Andrioid.Support packages. Downgrade to v23.3.0 will solve the porblem but for me this then means I have problems with compatibility with other nuget packages.

**Comment by Bobisback** [comment] 2017-03-31 18:57
Ya this is breaking for me as well. The issue is the xamarin forms map is accessing that field. It was suppose to be fixed in hte pre6 for xamarin forms. But it is still not working for me.

**Comment by TorbenK** [comment] 2017-04-21 12:49
There seem to be several issues with the Android Renderer and the new XF release. I don't know when I'll find time to fix this, help will be very much appreciated.

**Comment by Bobisback** [comment] 2017-04-21 13:55
Ya I am still having all kinds of issues with this. I will take a look, but I am not even sure that the error is not. It is just flat doing nothing when I hit the button to go to the map view. No exception or crash, the only thing in the log is this:

```
04-20 15:38:43.515 D/ViewRootImpl(21811): ViewPostImeInputStage processPointer 0
04-20 15:38:43.685 D/ViewRootImpl(21811): ViewPostImeInputStage processPointer 1
```

**Comment by TorbenK** [comment] 2017-04-28 10:09
It should work again with the current dev branch.

**Comment by kikolopes90** [comment] 2017-09-13 13:31
Same here =/

Because I'm using [Xamarin.Firebase.Crash](https://www.nuget.org/packages/Xamarin.Firebase.Crash/), it is necessary to update all Xamarin.GooglePlayServices version 42.1021.1 (latest), then an error appears that says System.MissingMethodException: Method 'Android.Gms.Maps.MapView.get_Map' not found.

Before without this Xamarin.Firebase.Crash and have Xamarin.GooglePlayServices version 29.0.0.1, it worked.

Ps: Sorry, bad google translate

**Comment by kikolopes90** [comment] 2017-09-13 14:18
I'm going to use "[Xamarin.FireBase.Crash](https://www.nuget.org/packages/Xamarin.Firebase.Crash/)", it is necessary to install or upgrade to "Xamarin.GooglePlayService v42.1021.1"

Using my app:
Xamarin Forms v2.3.4.270
Xamarin Forms Maps v2.3.4.270
Xamarin.GooglePlayService v42.1021.1 (Base, Basement, Location, Maps and Tasks)

I tested my app and it appears an error says:
```
09-13 15:01:48.229 I/MonoDroid( 9556): UNHANDLED EXCEPTION:
09-13 15:01:48.275 I/MonoDroid( 9556): System.ArgumentException: An item with the same key has already been added. Key: TK.CustomMap.Overlays.TKRoute
09-13 15:01:48.275 I/MonoDroid( 9556):   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000bb] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-13 15:01:48.275 I/MonoDroid( 9556):   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-13 15:01:48.275 I/MonoDroid( 9556):   at TK.CustomMap.Droid.TKCustomMapRenderer+<AddRoute>d__51.MoveNext () [0x00243] in <5b9d79f7c2904332851a10b98f67661f>:0 
09-13 15:01:48.275 I/MonoDroid( 9556): --- End of stack trace from previous location where exception was thrown ---
09-13 15:01:48.275 I/MonoDroid( 9556):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-13 15:01:48.275 I/MonoDroid( 9556):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-13 15:01:48.275 I/MonoDroid( 9556):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <7a2bbe1fcaec4467930361ae212aeea9>:0 
09-13 15:01:48.275 I/MonoDroid( 9556):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <7a2bbe1fcaec4467930361ae212aeea9>:0 
09-13 15:01:48.275 I/MonoDroid( 9556):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <7a2bbe1fcaec4467930361ae212aeea9>:0 
09-13 15:01:48.275 I/MonoDroid( 9556):   at (wrapper dynamic-method) System.Object:325a8233-a573-48c0-835a-47875a2023ee (intptr,intptr)
09-13 15:01:48.297 W/art     ( 9556): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
An unhandled exception occured.

09-13 15:01:48.817 E/mono    ( 9556): 
09-13 15:01:48.817 E/mono    ( 9556): Unhandled Exception:
09-13 15:01:48.817 E/mono    ( 9556): System.ArgumentException: An item with the same key has already been added. Key: TK.CustomMap.Overlays.TKRoute
09-13 15:01:48.817 E/mono-rt ( 9556): [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: An item with the same key has already been added. Key: TK.CustomMap.Overlays.TKRoute
```

**Closed as completed** 2017-10-24 09:49 UTC
Labels: bug, help wanted
